/**
 * `@visualizer-ui` — internal UI primitive library.
 *
 * Scope: UI components only. Pure utility functions (string formatting,
 * data transforms, etc.) do NOT belong here — they live in `src/lib/*`.
 *
 * All primitives in this module consume the global design tokens via CSS
 * variables (`var(--accent)`, `var(--bg-panel)`, etc.) and must never hard
 * code color or spacing literals. The token source is
 * `src/design/tokens.ts` + `src/design/motionTokens.ts`; CSS variables are
 * generated by `viteDesignTokensPlugin`.
 */
export { Button, type ButtonProps, type ButtonVariant, type ButtonSize } from "./primitives/Button";
export { IconButton, type IconButtonProps } from "./primitives/IconButton";
export { Switch, type SwitchProps, type SwitchSize } from "./primitives/Switch";
export {
  Dialog,
  type DialogProps,
  type DialogVariant,
  RadixDialog,
} from "./primitives/Dialog";
export {
  Toast,
  ToastProvider,
  type ToastProps,
} from "./primitives/Toast";
export { PanelCard, type PanelCardProps } from "./primitives/PanelCard";
export {
  Combobox,
  type ComboboxProps,
  type ComboboxRow,
  type ComboboxClasses,
  type ComboboxHandle,
  type ComboboxRenderRowArgs,
} from "./primitives/Combobox";
